"""NOLA-themed word pools for token generation.

Three pools of ~100 words each, yielding ~1,000,000 unique combinations.
Format: <place>-<music-adjective>-<nola-noun>
Example: "treme-funky-crawfish", "marigny-brassy-beignet"
"""

from itertools import combinations


def _levenshtein(a: str, b: str) -> int:
    """Compute Levenshtein edit distance between two strings."""
    if a == b:
        return 0
    if not a:
        return len(b)
    if not b:
        return len(a)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        curr = [i] + [0] * len(b)
        for j, cb in enumerate(b, 1):
            curr[j] = min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + (ca != cb))
        prev = curr
    return prev[len(b)]


POOL_PLACES: list[str] = [
    "treme",
    "marigny",
    "bywater",
    "frenchmen",
    "bourbon",
    "magazine",
    "decatur",
    "rampart",
    "esplanade",
    "chartres",
    "dauphine",
    "royal",
    "canal",
    "basin",
    "gentilly",
    "algiers",
    "uptown",
    "midcity",
    "lakeside",
    "bayou",
    "warehouse",
    "garden",
    "irish",
    "seventh",
    "backatown",
    "hollygrove",
    "broadmoor",
    "carrollton",
    "fontaine",
    "pirate",
    "jackson",
    "dumaine",
    "iberville",
    "gravier",
    "perdido",
    "poydras",
    "calliope",
    "melpomene",
    "terpsichore",
    "coliseum",
    "annunciation",
    "tchoupitoulas",
    "constance",
    "laurel",
    "octavia",
    "napoleon",
    "valence",
    "cadiz",
    "milan",
    # Additional NOLA neighborhoods, streets, and landmarks
    "lakeview",
    "leonidas",
    "oaklawn",
    "westbank",
    "riverbend",
    "audubon",
    "fontainebleau",
    "villere",
    "claiborne",
    "clio",
    "thalia",
    "erato",
    "euterpe",
    "polymnia",
    "urania",
    "nayades",
    "desire",
    "pauger",
    "marais",
    "henriette",
    "piety",
    "abundance",
    "clouet",
    "caffin",
    "almonaster",
    "st",
    "tulane",
    "loyola",
    "carondelet",
    "prytania",
    "camp",
    "felicity",
    "josephine",
    "religious",
    "harmony",
    "euclid",
    "chalmette",
    "burthe",
    "elysian",
    "leontine",
    "dufossat",
    "calhoun",
    "jeannette",
    "walmsley",
    "nashville",
    "arabella",
    "soniat",
    "bordeaux",
    "dublin",
    "colbert",
]

POOL_MUSIC: list[str] = [
    "funky",
    "jazzy",
    "stomping",
    "rolling",
    "syncopated",
    "groovy",
    "soulful",
    "brassy",
    "bluesy",
    "bouncing",
    "strutting",
    "riffing",
    "sliding",
    "honking",
    "wailing",
    "crooning",
    "belting",
    "grooving",
    "shuffling",
    "clapping",
    "tapping",
    "rumbling",
    "humming",
    "howling",
    "singing",
    "drumming",
    "strumming",
    "picking",
    "blowing",
    "marching",
    "dancing",
    "prancing",
    "stepping",
    "twirling",
    "bopping",
    "jamming",
    "vamping",
    "comping",
    "soloing",
    "mellow",
    "brisk",
    "lively",
    "fiery",
    "smooth",
    "snappy",
    "peppy",
    "bold",
    "sweet",
    "wild",
    # Additional music-related adjectives
    "swampy",
    "driving",
    "lilting",
    "swelling",
    "surging",
    "pulsing",
    "rippling",
    "soaring",
    "drifting",
    "floating",
    "punchy",
    "gritty",
    "silky",
    "smoky",
    "sultry",
    "earthy",
    "spirited",
    "stirring",
    "rousing",
    "swaying",
    "rocking",
    "reeling",
    "moaning",
    "chanting",
    "hollering",
    "calling",
    "pounding",
    "throbbing",
    "churning",
    "stompy",
    "spiraling",
    "echoing",
    "reverbing",
    "pumping",
    "shaking",
    "rattling",
    "clanging",
    "honky",
    "bluegrassy",
    "rootsy",
    "righteous",
    "lowdown",
    "upbeat",
    "halftime",
    "offbeat",
    "backbeat",
    "downbeat",
]

POOL_NOLA: list[str] = [
    "crawfish",
    "beignet",
    "gumbo",
    "praline",
    "flambeaux",
    "parasol",
    "pelican",
    "magnolia",
    "streetcar",
    "shotgun",
    "kingcake",
    "hurricane",
    "sazerac",
    "roux",
    "andouille",
    "boudin",
    "etouffee",
    "tabasco",
    "oyster",
    "shrimp",
    "trumpet",
    "trombone",
    "tuba",
    "washboard",
    "snaredrum",
    "accordion",
    "fiddle",
    "tambourine",
    "cowbell",
    "saxophone",
    "muffuletta",
    "jambalaya",
    "bisque",
    "grillades",
    "chicory",
    "doubloon",
    "krewe",
    "lagniappe",
    "pirogue",
    "zydeco",
    "nutria",
    "heron",
    "egret",
    "ibis",
    "alligator",
    "cypress",
    "moss",
    "levee",
    "crescent",
    "voodoo",
    # Additional food, instruments, and cultural items
    "banjo",
    "clarinet",
    "cornet",
    "sousaphone",
    "bass",
    "guitar",
    "piano",
    "harmonica",
    "vibraphone",
    "marimba",
    "conga",
    "bongo",
    "snare",
    "cajon",
    "banquette",
    "balcony",
    "courtyard",
    "ironwork",
    "gaslight",
    "medallion",
    "neutral",
    "batture",
    "faubourg",
    "atchafalaya",
    "pontchartrain",
    "manchac",
    "camellia",
    "jasmine",
    "azalea",
    "wisteria",
    "pecan",
    "satsuma",
    "mirliton",
    "tasso",
    "filé",
    "remoulade",
    "bananas",
    "bread",
    "calas",
    "camelback",
    "doberge",
    "debris",
    "drago",
    "gris",
    "laissez",
    "cher",
    "lundi",
    "mardi",
    "masque",
    "reveler",
]


_MAX_SAFE_LEVENSHTEIN_DISTANCE = 1


def validate_word_pools() -> list[tuple[str, str, int]]:
    """Check for ambiguous word pairs across all pools.

    Returns list of (word1, word2, distance) pairs where distance <= 1,
    meaning the fuzzy resolver might confuse them.
    """
    all_words = POOL_PLACES + POOL_MUSIC + POOL_NOLA
    return [
        (w1, w2, _levenshtein(w1, w2))
        for w1, w2 in combinations(all_words, 2)
        if _levenshtein(w1, w2) <= _MAX_SAFE_LEVENSHTEIN_DISTANCE
    ]


# Backward-compatible alias
validate_pools = validate_word_pools
