"""NOLA-themed word pools for token generation.

Three pools of ~100 words each, yielding ~1,000,000 unique combinations.
Format: <adjective/adverb>-<verb/adjective>-<noun>
Example: "wildly-dancing-krewe", "pythonic-brass-parrot"

POOL1: Adverbs and adjectives — New Orleans, music, and festival themed,
       with some Monty Python humor.
POOL2: Verbs and adjectives — musical and festival actions and descriptors.
POOL3: Nouns — New Orleans culture, instruments, interesting animals,
       and Monty Python references.

For backward compatibility, the legacy pools (POOL_PLACES, POOL_MUSIC, POOL_NOLA)
from the original schema are retained as LEGACY_POOL_PLACES, LEGACY_POOL_MUSIC,
and LEGACY_POOL_NOLA for token resolution purposes only. They are not used for
generating new tokens.
"""

from itertools import combinations


def levenshtein_distance(a: str, b: str) -> int:
    """Compute Levenshtein edit distance between two strings."""
    if a == b:
        return 0
    if not a:
        return len(b)
    if not b:
        return len(a)
    prev = list(range(len(b) + 1))
    for i, ca in enumerate(a, 1):
        curr = [i] + [0] * len(b)
        for j, cb in enumerate(b, 1):
            curr[j] = min(prev[j] + 1, curr[j - 1] + 1, prev[j - 1] + (ca != cb))
        prev = curr
    return prev[len(b)]


# ── POOL1: Adverbs and adjectives ─────────────────────────────────────────────
# New Orleans, music, festival themed — plus Monty Python humor.
POOL1: list[str] = [
    # adverbs
    "wildly",
    "boldly",
    "deeply",
    "freely",
    "truly",
    "madly",
    "hotly",
    "coolly",
    "richly",
    "warmly",
    "gladly",
    "softly",
    "firmly",
    "slowly",
    "swiftly",
    "sharply",
    "darkly",
    "lively",
    "wholly",
    "partly",
    # adjectives — music and festival
    "jazzy",
    "funky",
    "golden",
    "bluesy",
    "swampy",
    "sultry",
    "smoky",
    "groovy",
    "earthy",
    "rootsy",
    "gritty",
    "silky",
    "punchy",
    "stompy",
    "soulful",
    "sacred",
    "fiery",
    "mellow",
    "peppy",
    "snappy",
    "lush",
    "bold",
    "sweet",
    "crisp",
    "vivid",
    "bright",
    "sharp",
    "dense",
    "thick",
    "smooth",
    # NOLA themed
    "creole",
    "voodoo",
    "bayou",
    "festive",
    "zydeco",
    "treme",
    "uptown",
    "lakeside",
    "bourbony",
    "marigny",
    "crescent",
    "laissez",
    "spirited",
    "stirring",
    "rousing",
    "righteous",
    "lowdown",
    "offbeat",
    "backbeat",
    "secondline",
    # Monty Python humor
    "pythonic",
    "knightly",
    "spanishy",
    "galahad",
    "bravely",
    "absurdly",
    "chivalric",
    "enquirer",
    "questing",
    "legendary",
    "ordained",
    "camelot",
    "bridgeward",
    "exceeding",
    "shrublike",
    "coconutty",
    "naughty",
    "silenced",
    "foretold",
    "verily",
]

# ── POOL2: Verbs and adjectives ───────────────────────────────────────────────
# Musical / festival actions and descriptors.
POOL2: list[str] = [
    # verbs — musical actions
    "dancing",
    "strutting",
    "waltzing",
    "riffing",
    "weaving",
    "honking",
    "wailing",
    "crooning",
    "belting",
    "grooving",
    "shuffling",
    "clapping",
    "tapping",
    "rumbling",
    "howling",
    "singing",
    "drumming",
    "strumming",
    "picking",
    "tooting",
    "marching",
    "prancing",
    "stepping",
    "twirling",
    "bopping",
    "jamming",
    "vamping",
    "comping",
    "soloing",
    "rolling",
    "stomping",
    "swaying",
    "rocking",
    "reeling",
    "moaning",
    "chanting",
    "calling",
    "pounding",
    "throbbing",
    "churning",
    "spiraling",
    "pumping",
    "shaking",
    "rattling",
    "clanging",
    "hollering",
    "driving",
    "surging",
    "pulsing",
    "rippling",
    # adjectives — musical descriptors
    "brass",
    "syncopated",
    "upbeat",
    "halftime",
    "downbeat",
    "lilting",
    "swelling",
    "soaring",
    "drifting",
    "floating",
    "bouncing",
    "brisk",
    "snazzy",
    "bracing",
    "crashing",
    "gliding",
    "spinning",
    "blazing",
    "charging",
    "billowing",
    "thundering",
    "crackling",
    "flaring",
    "sparkling",
    "gleaming",
    "shining",
    "burning",
    "flashing",
    "glowing",
    "humming",
    "buzzing",
    "vibrating",
    "echoing",
    "reverbing",
    "cascading",
    "careening",
    "rushing",
    "coursing",
    "dazzling",
    "radiant",
    "luminous",
    "vibrant",
    "pulsating",
    "jubilant",
    "exultant",
    "fervent",
    "ardent",
    "strident",
    "resonant",
]

# ── POOL3: Nouns ──────────────────────────────────────────────────────────────
# New Orleans culture, instruments, interesting animals, Monty Python refs.
POOL3: list[str] = [
    # NOLA food and culture
    "krewe",
    "gumbo",
    "praline",
    "beignet",
    "flambeaux",
    "parasol",
    "kingcake",
    "sazerac",
    "andouille",
    "boudin",
    "etouffee",
    "muffuletta",
    "jambalaya",
    "doubloon",
    "lagniappe",
    "pirogue",
    "faubourg",
    "banquette",
    "ironwork",
    "balcony",
    "levee",
    "lagoon",
    "bayouside",
    "shotgun",
    "streetcar",
    "magnolia",
    "camellia",
    "tabasco",
    "remoulade",
    "chicory",
    "satsuma",
    "mirliton",
    "doberge",
    "filefest",
    "roux",
    # instruments
    "trumpet",
    "trombone",
    "tuba",
    "accordion",
    "fiddle",
    "tambourine",
    "saxophone",
    "washboard",
    "sousaphone",
    "clarinet",
    "cornet",
    "vibraphone",
    "marimba",
    "harmonica",
    "snaredrum",
    "conga",
    "cajon",
    "banjo",
    "mandolin",
    "zither",
    # interesting animals
    "pelican",
    "alligator",
    "nutria",
    "egret",
    "flamingo",
    "iguana",
    "chameleon",
    "mongoose",
    "capybara",
    "axolotl",
    "pangolin",
    "narwhal",
    "cassowary",
    "kinkajou",
    "ocelot",
    "tapir",
    "wombat",
    "quokka",
    "marmot",
    "sloth",
    "toucan",
    "hornbill",
    "lorikeet",
    "gallinule",
    "roseate",
    # Monty Python references
    "parrot",
    "swallow",
    "shrubbery",
    "grail",
    "enchanter",
    "herring",
    "coconut",
    "catapult",
    "horseman",
    "bridgekeeper",
    "lumberjack",
    "mortician",
    "fishslap",
    "inquisitor",
]

# ── Backward-compatible aliases ────────────────────────────────────────────────
# POOL_PLACES, POOL_MUSIC, and POOL_NOLA now point to the new pools.
# Code that imported these names continues to work unchanged.
POOL_PLACES: list[str] = POOL1
POOL_MUSIC: list[str] = POOL2
POOL_NOLA: list[str] = POOL3

# ── Legacy pools (for resolving tokens minted from the old scheme) ─────────────
# NOT used for new token generation. Used by fuzzy_resolve to accept old tokens.
LEGACY_POOL_PLACES: list[str] = [
    "treme",
    "bywater",
    "frenchmen",
    "bourbon",
    "magazine",
    "decatur",
    "rampart",
    "esplanade",
    "chartres",
    "dauphine",
    "royal",
    "canal",
    "basin",
    "gentilly",
    "algiers",
    "midcity",
    "warehouse",
    "garden",
    "irish",
    "seventh",
    "backatown",
    "hollygrove",
    "broadmoor",
    "carrollton",
    "fontaine",
    "pirate",
    "jackson",
    "dumaine",
    "iberville",
    "gravier",
    "perdido",
    "poydras",
    "calliope",
    "melpomene",
    "terpsichore",
    "coliseum",
    "annunciation",
    "tchoupitoulas",
    "constance",
    "laurel",
    "octavia",
    "napoleon",
    "valence",
    "cadiz",
    "milan",
    "lakeview",
    "leonidas",
    "oaklawn",
    "westbank",
    "riverbend",
    "audubon",
    "fontainebleau",
    "villere",
    "claiborne",
    "clio",
    "thalia",
    "erato",
    "euterpe",
    "polymnia",
    "urania",
    "nayades",
    "desire",
    "pauger",
    "marais",
    "henriette",
    "piety",
    "abundance",
    "clouet",
    "caffin",
    "almonaster",
    "tulane",
    "loyola",
    "carondelet",
    "prytania",
    "camp",
    "felicity",
    "josephine",
    "religious",
    "harmony",
    "euclid",
    "chalmette",
    "burthe",
    "elysian",
    "leontine",
    "dufossat",
    "calhoun",
    "jeannette",
    "walmsley",
    "nashville",
    "arabella",
    "soniat",
    "bordeaux",
    "dublin",
    "colbert",
]

LEGACY_POOL_MUSIC: list[str] = [
    "stomping",
    "rolling",
    "bouncing",
    "sliding",
    "honking",
    "grooving",
    "shuffling",
    "clapping",
    "tapping",
    "rumbling",
    "singing",
    "drumming",
    "strumming",
    "picking",
    "blowing",
    "marching",
    "prancing",
    "stepping",
    "twirling",
    "bopping",
    "jamming",
    "vamping",
    "comping",
    "soloing",
    "brisk",
    "fiery",
    "wild",
    "swampy",
    "driving",
    "lilting",
    "swelling",
    "surging",
    "pulsing",
    "rippling",
    "soaring",
    "drifting",
    "floating",
    "punchy",
    "gritty",
    "silky",
    "smoky",
    "sultry",
    "earthy",
    "spirited",
    "stirring",
    "rousing",
    "swaying",
    "rocking",
    "reeling",
    "moaning",
    "chanting",
    "hollering",
    "calling",
    "pounding",
    "throbbing",
    "churning",
    "stompy",
    "spiraling",
    "echoing",
    "reverbing",
    "pumping",
    "shaking",
    "rattling",
    "clanging",
    "honky",
    "bluegrassy",
    "rootsy",
    "righteous",
    "lowdown",
    "upbeat",
    "halftime",
    "offbeat",
    "backbeat",
    "downbeat",
    "lively",
    "snappy",
    "mellow",
    "bold",
    "sweet",
    "funky",
    "jazzy",
    "brassy",
    "bluesy",
    "groovy",
    "soulful",
]

LEGACY_POOL_NOLA: list[str] = [
    "crawfish",
    "beignet",
    "gumbo",
    "praline",
    "flambeaux",
    "parasol",
    "pelican",
    "magnolia",
    "streetcar",
    "shotgun",
    "kingcake",
    "hurricane",
    "sazerac",
    "roux",
    "andouille",
    "boudin",
    "etouffee",
    "tabasco",
    "oyster",
    "shrimp",
    "trumpet",
    "trombone",
    "tuba",
    "washboard",
    "snaredrum",
    "accordion",
    "fiddle",
    "tambourine",
    "cowbell",
    "saxophone",
    "muffuletta",
    "jambalaya",
    "bisque",
    "grillades",
    "chicory",
    "doubloon",
    "krewe",
    "lagniappe",
    "pirogue",
    "zydeco",
    "nutria",
    "heron",
    "egret",
    "ibis",
    "alligator",
    "cypress",
    "moss",
    "levee",
    "crescent",
    "voodoo",
    "banjo",
    "clarinet",
    "cornet",
    "sousaphone",
    "bass",
    "guitar",
    "piano",
    "harmonica",
    "vibraphone",
    "marimba",
    "conga",
    "bongo",
    "snare",
    "cajon",
    "banquette",
    "balcony",
    "courtyard",
    "ironwork",
    "gaslight",
    "medallion",
    "neutral",
    "batture",
    "faubourg",
    "atchafalaya",
    "pontchartrain",
    "manchac",
    "camellia",
    "jasmine",
    "azalea",
    "wisteria",
    "pecan",
    "satsuma",
    "mirliton",
    "tasso",
    "remoulade",
    "bananas",
    "calas",
    "camelback",
    "doberge",
    "debris",
    "laissez",
    "mardi",
    "masque",
    "reveler",
]

_MAX_SAFE_LEVENSHTEIN_DISTANCE = 1


def validate_word_pools() -> list[tuple[str, str, int]]:
    """Check for ambiguous word pairs across the active pools (POOL1, POOL2, POOL3).

    Returns list of (word1, word2, distance) pairs where distance <= 1,
    meaning the fuzzy resolver might confuse them.
    """
    all_words = POOL1 + POOL2 + POOL3
    return [
        (w1, w2, d)
        for w1, w2 in combinations(all_words, 2)
        if (d := levenshtein_distance(w1, w2)) <= _MAX_SAFE_LEVENSHTEIN_DISTANCE
    ]


# Backward-compatible alias
validate_pools = validate_word_pools
