"""Saturday April 18, 2026 — FQF schedule data."""

from fqf.models import (
    ABITA,
    CAFEBEIGNET,
    DUTCHALLEY,
    ENTERGY,
    FISHFRY,
    FRENCHMARKET,
    HANCOCK,
    HOUSEOFBLUES,
    JACKDANIELS,
    JAZZPARK,
    JAZZPLAYHOUSE,
    KREWE,
    LOYOLA,
    NEWORLEANS,
    OMNI,
    PANAMLIFE,
    SAT,
    SCHOOLHOUSE,
    TROPICAL,
    WILLOW,
    Act,
    t,
)

SATURDAY_ACTS: list[Act] = [
    Act("Gregg Martinez & the Delta Kings", ABITA, SAT, t(11, 30), t(12, 30)),
    Act("Ryan Batiste and Raw Revolution", ABITA, SAT, t(12, 50), t(13, 50)),
    Act("Big Chief Monk Boudreaux and the Golden Eagles", ABITA, SAT, t(14, 10), t(15, 10)),
    Act("Dawn Richard", ABITA, SAT, t(15, 30), t(16, 30)),
    Act("George Porter Jr & Runnin' Pardners", ABITA, SAT, t(17, 0), t(18, 20)),
    Act("Flow Tribe", ABITA, SAT, t(18, 40), t(20, 0)),
    Act("Tim Laughlin", NEWORLEANS, SAT, t(11, 15), t(12, 35)),
    Act("The Big Easy Boys", NEWORLEANS, SAT, t(12, 45), t(14, 0)),
    Act("Wendell Brunious", NEWORLEANS, SAT, t(14, 20), t(15, 30)),
    Act("Charmaine Neville", NEWORLEANS, SAT, t(15, 50), t(17, 0)),
    Act("James Andrews", NEWORLEANS, SAT, t(17, 20), t(18, 45)),
    Act("Christian Serpas & Ghost Town", TROPICAL, SAT, t(11, 10), t(12, 10)),
    Act("Ovi-G presents 'Xtra Cash!'", TROPICAL, SAT, t(12, 30), t(13, 30)),
    Act("Ronnie Lamarque Orchestra feat. Hot Rod Lincoln", TROPICAL, SAT, t(14, 0), t(15, 15)),
    Act("Victor Campbell & Timba Swamp", TROPICAL, SAT, t(15, 35), t(16, 35)),
    Act("Flagboy Giz & the Wild Tchoupitoulas", TROPICAL, SAT, t(16, 55), t(17, 55)),
    Act("Higher Heights Reggae Band", TROPICAL, SAT, t(18, 15), t(19, 45)),
    Act("Lily Unless and The If Onlys", JACKDANIELS, SAT, t(11, 10), t(12, 30)),
    Act("Paul Sanchez", JACKDANIELS, SAT, t(12, 50), t(13, 50)),
    Act("Water Seed", JACKDANIELS, SAT, t(14, 10), t(15, 10)),
    Act("Iceman Special", JACKDANIELS, SAT, t(15, 30), t(16, 40)),
    Act("The Original Pinettes Brass Band", JACKDANIELS, SAT, t(17, 0), t(18, 20)),
    Act("Big Freedia", JACKDANIELS, SAT, t(18, 50), t(20, 0)),
    Act("Bruce Daigrepont Cajun Band", WILLOW, SAT, t(11, 10), t(12, 20)),
    Act("Magnolia Sisters", WILLOW, SAT, t(12, 40), t(13, 50)),
    Act("Donna Angelle & the Zydeco Posse", WILLOW, SAT, t(14, 10), t(15, 10)),
    Act("Corey Ledet Zydeco & Black Magic", WILLOW, SAT, t(15, 30), t(16, 40)),
    Act("Dwayne Dopsie and the Zydeco Hellraisers", WILLOW, SAT, t(17, 0), t(18, 10)),
    Act("Sweet Crude", WILLOW, SAT, t(18, 30), t(20, 0)),
    Act("Loyola University Commercial Ensemble", LOYOLA, SAT, t(11, 0), t(12, 15)),
    Act("Joy Clark", LOYOLA, SAT, t(12, 35), t(13, 45)),
    Act("Tay/Heavensworld/Ja Fierce & Azure Skye et al.", LOYOLA, SAT, t(14, 10), t(15, 30)),
    Act("Mia Borders", LOYOLA, SAT, t(15, 50), t(17, 10)),
    Act("John 'Papa' Gros", LOYOLA, SAT, t(17, 30), t(19, 0)),
    Act("Red Wolf Brass Band", FISHFRY, SAT, t(11, 10), t(12, 30)),
    Act("DJ Hollaback", FISHFRY, SAT, t(12, 35), t(13, 5)),
    Act("Storyville Stompers Brass Band", FISHFRY, SAT, t(13, 10), t(14, 30)),
    Act("DJ Spin", FISHFRY, SAT, t(14, 35), t(15, 15)),
    Act("Original Hurricane Brass Band", FISHFRY, SAT, t(15, 20), t(16, 40)),
    Act("DJ RQ Away", FISHFRY, SAT, t(16, 45), t(17, 30)),
    Act("Big 6 Brass Band", FISHFRY, SAT, t(17, 35), t(18, 55)),
    Act("DJ Poppa", FISHFRY, SAT, t(19, 0), t(20, 0)),
    Act("John Rankin", ENTERGY, SAT, t(11, 0), t(11, 55)),
    Act("Beth Patterson", ENTERGY, SAT, t(12, 15), t(13, 10)),
    Act("Kyle Alexander", ENTERGY, SAT, t(13, 30), t(14, 25)),
    Act("Daphne Parker Powell", ENTERGY, SAT, t(14, 45), t(15, 45)),
    Act("AdoSoul and the Tribe", ENTERGY, SAT, t(16, 5), t(17, 0)),
    Act("Legendary Barbara Shorts and Blue Jazz", PANAMLIFE, SAT, t(11, 0), t(12, 10)),
    Act("Lynn Drury", PANAMLIFE, SAT, t(12, 30), t(13, 30)),
    Act("Vivaz", PANAMLIFE, SAT, t(13, 50), t(14, 50)),
    Act("Ever More Nest", PANAMLIFE, SAT, t(15, 10), t(16, 10)),
    Act("Troy Sawyer and the Elementz", PANAMLIFE, SAT, t(16, 30), t(17, 50)),
    Act("Fermín Ceballos + Merengue4FOUR", PANAMLIFE, SAT, t(18, 10), t(19, 30)),
    Act("Audrey Lecrone", JAZZPLAYHOUSE, SAT, t(11, 0), t(13, 30)),
    Act("The Wolfe Johns Blues Band", JAZZPLAYHOUSE, SAT, t(14, 0), t(16, 30)),
    Act("Richard 'Piano' Scott & The Twisty River Band", JAZZPLAYHOUSE, SAT, t(17, 0), t(19, 30)),
    Act("Secret Six Jazz Band", FRENCHMARKET, SAT, t(11, 30), t(13, 0)),
    Act(
        "Special Dance Performance by the NOLA Chorus Girls", FRENCHMARKET, SAT, t(13, 0), t(13, 5)
    ),
    Act("New Orleans Cottonmouth Kings", FRENCHMARKET, SAT, t(13, 30), t(15, 0)),
    Act("Alicia Renee aka Blue Eyes Sextet", FRENCHMARKET, SAT, t(15, 30), t(17, 0)),
    Act("The Jump Hounds", FRENCHMARKET, SAT, t(17, 30), t(19, 0)),
    Act("Kid Simmons Jazz Band", DUTCHALLEY, SAT, t(11, 15), t(12, 30)),
    Act("Stephen Walker N'Em Swinging in New Orleans", DUTCHALLEY, SAT, t(12, 45), t(14, 0)),
    Act("Kevin Ray Clark and Bourbon Street All Stars", DUTCHALLEY, SAT, t(14, 15), t(15, 30)),
    Act("New Orleans Ragtime Orchestra ft. Lars Edegran", DUTCHALLEY, SAT, t(15, 45), t(17, 0)),
    Act("Tiago Guy & Renee Gros", HOUSEOFBLUES, SAT, t(11, 15), t(12, 30)),
    Act("Pocket Chocolate", HOUSEOFBLUES, SAT, t(12, 45), t(14, 45)),
    Act("Jamey St. Pierre", HOUSEOFBLUES, SAT, t(15, 0), t(17, 0)),
    Act("Eric Johanson", HOUSEOFBLUES, SAT, t(17, 15), t(19, 15)),
    Act("Sansone & John Fohl", HOUSEOFBLUES, SAT, t(19, 30), t(21, 30)),
    Act("Congo Square Preservation Society", JAZZPARK, SAT, t(11, 0), t(12, 0)),
    Act("Jamil Sharif Quartet", JAZZPARK, SAT, t(12, 15), t(13, 15)),
    Act("Shake Em Up Jazz Band", JAZZPARK, SAT, t(13, 30), t(14, 30)),
    Act("Young Tuxedo Brass Band", JAZZPARK, SAT, t(14, 45), t(15, 45)),
    Act("Saskia Walker Big Band", JAZZPARK, SAT, t(16, 0), t(17, 0)),
    Act("Lycée Français Musicians", SCHOOLHOUSE, SAT, t(11, 0), t(12, 0)),
    Act("Pierre A Capdau Marching Jaguars", SCHOOLHOUSE, SAT, t(12, 20), t(13, 20)),
    Act("McMain Singing Mustangs", SCHOOLHOUSE, SAT, t(13, 50), t(14, 50)),
    Act("The Roots of Music", SCHOOLHOUSE, SAT, t(15, 10), t(16, 10)),
    Act("Audubon Charter School R&B Choir", SCHOOLHOUSE, SAT, t(16, 30), t(17, 30)),
    Act("Clive Wilson's New Orleans Serenaders", HANCOCK, SAT, t(11, 30), t(12, 45)),
    Act("Caleb Tokarska", HANCOCK, SAT, t(13, 0), t(14, 15)),
    Act("John Mahoney Little Band", HANCOCK, SAT, t(14, 30), t(15, 45)),
    Act("Steve Pistorius & the Southern Syncopators", HANCOCK, SAT, t(16, 0), t(17, 15)),
    Act("Garden District Jazz Band", OMNI, SAT, t(11, 15), t(12, 30)),
    Act("Marlon Jordan and Quartet", OMNI, SAT, t(12, 45), t(14, 0)),
    Act("Louis Michot and Swamp Magic", OMNI, SAT, t(14, 15), t(15, 30)),
    Act("The Crybabies", OMNI, SAT, t(15, 45), t(17, 0)),
    Act("Bad Penny Pleasuremakers", KREWE, SAT, t(11, 0), t(12, 15)),
    Act("Washboard Chaz Blues Trio", KREWE, SAT, t(12, 30), t(13, 45)),
    Act("Nanci Zhang", KREWE, SAT, t(14, 0), t(15, 15)),
    Act("Aurora Nealand & the Royal Roses", KREWE, SAT, t(15, 30), t(16, 45)),
    Act("The Beignet Orchestra", CAFEBEIGNET, SAT, t(11, 30), t(14, 0)),
    Act("Zach Wiggins Trio", CAFEBEIGNET, SAT, t(14, 30), t(17, 0)),
]
