"""Sunday April 19, 2026 — FQF schedule data."""

from fqf.models import (
    ABITA,
    CAFEBEIGNET,
    DUTCHALLEY,
    ENTERGY,
    FISHFRY,
    FRENCHMARKET,
    HANCOCK,
    HOUSEOFBLUES,
    JACKDANIELS,
    JAZZPARK,
    JAZZPLAYHOUSE,
    KREWE,
    LOYOLA,
    NEWORLEANS,
    OMNI,
    PANAMLIFE,
    SCHOOLHOUSE,
    SUN,
    TROPICAL,
    WILLOW,
    Act,
    t,
)

SUNDAY_ACTS: list[Act] = [
    Act("Sam Price & the True Believers", ABITA, SUN, t(11, 30), t(12, 30)),
    Act("Bucktown All-Stars", ABITA, SUN, t(12, 50), t(13, 50)),
    Act("New Orleans Suspects", ABITA, SUN, t(14, 10), t(15, 10)),
    Act("Jelly Joseph", ABITA, SUN, t(15, 30), t(16, 30)),
    Act("Hasizzle with TBC Brass Band", ABITA, SUN, t(17, 0), t(18, 20)),
    Act("Cyril Neville", ABITA, SUN, t(18, 50), t(20, 0)),
    Act("Tuba Skinny", NEWORLEANS, SUN, t(11, 15), t(12, 25)),
    Act("Lena Prima", NEWORLEANS, SUN, t(12, 45), t(14, 0)),
    Act("Jeremy Davenport", NEWORLEANS, SUN, t(14, 20), t(15, 30)),
    Act("Judith Owen & Her Gentlemen Callers", NEWORLEANS, SUN, t(15, 50), t(17, 10)),
    Act("Delfeayo Marsalis & the Uptown Jazz Orchestra", NEWORLEANS, SUN, t(17, 30), t(18, 45)),
    Act("Professor Craig Adams & the Higher Dimensions Band", TROPICAL, SUN, t(11, 10), t(12, 10)),
    Act("Alex McMurray", TROPICAL, SUN, t(12, 30), t(13, 30)),
    Act("Assata Renay", TROPICAL, SUN, t(13, 50), t(14, 50)),
    Act("Wanda Rouzan and a Taste of New Orleans", TROPICAL, SUN, t(15, 10), t(16, 10)),
    Act("Big Frank & Lil Frank & the Dirty Old Men", TROPICAL, SUN, t(16, 30), t(17, 45)),
    Act("Honey Island Swamp Band", TROPICAL, SUN, t(18, 15), t(19, 45)),
    Act("Roderick 'Rev' Paulin and The Congregation", JACKDANIELS, SUN, t(11, 10), t(12, 30)),
    Act("Jason Neville Funky Soul Allstar Band", JACKDANIELS, SUN, t(12, 50), t(13, 50)),
    Act("Gumbeaux Juice", JACKDANIELS, SUN, t(14, 10), t(15, 10)),
    Act("The Rumble featuring Chief Joseph Boudreaux Jr", JACKDANIELS, SUN, t(15, 30), t(16, 30)),
    Act("Irma Thomas, Soul Queen of New Orleans", JACKDANIELS, SUN, t(17, 0), t(18, 10)),
    Act("Cupid & the Dance Party Express Band", JACKDANIELS, SUN, t(18, 40), t(20, 0)),
    Act("Les Femmes Farouches", WILLOW, SUN, t(11, 10), t(12, 20)),
    Act("Cameron Dupuy & the Cajun Troubadours", WILLOW, SUN, t(12, 40), t(13, 50)),
    Act("Yvette Landry & the Jukes", WILLOW, SUN, t(14, 10), t(15, 10)),
    Act(
        "Buckwheat Zydeco Jr. & The Legendary Ils Sont Partis Band",
        WILLOW,
        SUN,
        t(15, 30),
        t(16, 40),
    ),
    Act("Chubby Carrier and the Bayou Swamp Band", WILLOW, SUN, t(17, 0), t(18, 10)),
    Act("Rockin' Dopsie Jr. & the Zydeco Twisters", WILLOW, SUN, t(18, 40), t(20, 0)),
    Act("Casme", LOYOLA, SUN, t(11, 0), t(12, 0)),
    Act("Across Phoenix, James Wyzten, Kissing Disease", LOYOLA, SUN, t(12, 20), t(13, 35)),
    Act("Kristin Diable", LOYOLA, SUN, t(13, 55), t(14, 50)),
    Act("Helen Gillet: ReBelle Musique", LOYOLA, SUN, t(15, 10), t(16, 10)),
    Act("Creole String Beans", LOYOLA, SUN, t(16, 30), t(17, 30)),
    Act("Astral Project", LOYOLA, SUN, t(17, 50), t(19, 0)),
    Act("Smokin' on Some Brass", FISHFRY, SUN, t(11, 10), t(12, 20)),
    Act("New Birth Brass Band", FISHFRY, SUN, t(12, 40), t(14, 0)),
    Act("DJ Vintage", FISHFRY, SUN, t(14, 5), t(14, 35)),
    Act("Kings of Brass", FISHFRY, SUN, t(14, 40), t(16, 0)),
    Act("DJ ODD Spinz", FISHFRY, SUN, t(16, 5), t(16, 35)),
    Act("Hot 8 Brass Band", FISHFRY, SUN, t(16, 40), t(17, 45)),
    Act("ANTWIGADEE!", FISHFRY, SUN, t(17, 50), t(18, 35)),
    Act("New Breed", FISHFRY, SUN, t(18, 40), t(20, 0)),
    Act("Andy J Forest Treeaux", ENTERGY, SUN, t(11, 0), t(11, 55)),
    Act("Luke Allen", ENTERGY, SUN, t(12, 15), t(13, 10)),
    Act("Justin Garner", ENTERGY, SUN, t(13, 30), t(14, 25)),
    Act("Bobbi Rae", ENTERGY, SUN, t(14, 45), t(15, 45)),
    Act("Cristina Kaminis", ENTERGY, SUN, t(16, 5), t(17, 0)),
    Act("Bamboula 2000", PANAMLIFE, SUN, t(11, 10), t(12, 10)),
    Act("Anaïs St. John", PANAMLIFE, SUN, t(12, 30), t(13, 30)),
    Act("Papo y Son Mandao", PANAMLIFE, SUN, t(13, 50), t(14, 50)),
    Act("Los Güiros", PANAMLIFE, SUN, t(15, 10), t(16, 10)),
    Act("Stanton Moore featuring Joe Ashlar and Danny Abel", PANAMLIFE, SUN, t(16, 30), t(17, 50)),
    Act("Leyla McCalla", PANAMLIFE, SUN, t(18, 10), t(19, 30)),
    Act("Jenna McSwain Jazz Band", JAZZPLAYHOUSE, SUN, t(11, 0), t(13, 30)),
    Act("Jeanne Marie Harris", JAZZPLAYHOUSE, SUN, t(14, 0), t(16, 30)),
    Act("Gerald French & The Original Tuxedo Jazz Band", JAZZPLAYHOUSE, SUN, t(17, 0), t(19, 30)),
    Act("Smoking Time Jazz Club", FRENCHMARKET, SUN, t(11, 30), t(13, 0)),
    Act("Charlie Halloran and the Tropicales", FRENCHMARKET, SUN, t(13, 30), t(15, 0)),
    Act("The New Orleans Swinging Gypsies", FRENCHMARKET, SUN, t(15, 30), t(17, 0)),
    Act("Sullivan Dabney's Muzik Jazz Band", FRENCHMARKET, SUN, t(17, 30), t(19, 0)),
    Act("Hot Club of New Orleans", DUTCHALLEY, SUN, t(11, 15), t(12, 30)),
    Act("Mayumi Shara & New Orleans Jazz Letters", DUTCHALLEY, SUN, t(12, 45), t(14, 0)),
    Act("Jade Perdue", DUTCHALLEY, SUN, t(14, 15), t(15, 30)),
    Act("Tom Saunders and the Hotcats", DUTCHALLEY, SUN, t(15, 45), t(17, 0)),
    Act("Sophia Parigi", HOUSEOFBLUES, SUN, t(12, 30), t(14, 30)),
    Act("Sean Riley", HOUSEOFBLUES, SUN, t(15, 0), t(17, 0)),
    Act("Craig Klein's New Orleans Allstars", JAZZPARK, SUN, t(11, 0), t(12, 0)),
    Act("Matt Lemmler presents 'New Orleans in Stride'", JAZZPARK, SUN, t(12, 15), t(13, 15)),
    Act("Crescent City Sisters", JAZZPARK, SUN, t(13, 30), t(14, 30)),
    Act("Louis Ford", JAZZPARK, SUN, t(14, 45), t(15, 45)),
    Act("Arrowhead Jazz Band feat. NPS Rangers et al.", JAZZPARK, SUN, t(16, 0), t(17, 0)),
    Act("Greater New Orleans Youth Orchestras", SCHOOLHOUSE, SUN, t(11, 0), t(12, 0)),
    Act("Chalmette High School Marching Band", SCHOOLHOUSE, SUN, t(12, 20), t(13, 20)),
    Act("St. Mary's Academy Gospel Choir", SCHOOLHOUSE, SUN, t(13, 50), t(14, 50)),
    Act("Don Jamison Heritage School of Music", SCHOOLHOUSE, SUN, t(15, 10), t(16, 10)),
    Act("Walter L. Cohen High School Marching Band", SCHOOLHOUSE, SUN, t(16, 30), t(17, 30)),
    Act("Kid Merv & All That Jazz", HANCOCK, SUN, t(11, 30), t(12, 45)),
    Act("Miss Sophie Lee", HANCOCK, SUN, t(13, 0), t(14, 15)),
    Act("Mark Brooks", HANCOCK, SUN, t(14, 30), t(15, 45)),
    Act("New Orleans High Society", HANCOCK, SUN, t(16, 0), t(17, 15)),
    Act("Jason Mingledorff", OMNI, SUN, t(11, 15), t(12, 30)),
    Act("Father Ron and Friends", OMNI, SUN, t(12, 45), t(14, 0)),
    Act("Sweetie Pies of New Orleans", OMNI, SUN, t(14, 15), t(15, 30)),
    Act("Ecirb Müller's Twisted Dixie", OMNI, SUN, t(15, 45), t(17, 0)),
    Act("Capivaras Jazz Quartet", KREWE, SUN, t(11, 0), t(12, 15)),
    Act("The New Orleans Jazz Vipers", KREWE, SUN, t(12, 30), t(13, 45)),
    Act("Seva Venet's Traditional Line-Up", KREWE, SUN, t(14, 0), t(15, 15)),
    Act("Harry Mayronne & Chloe Marie", KREWE, SUN, t(15, 30), t(16, 45)),
    Act("Steamboat Willy", CAFEBEIGNET, SUN, t(11, 30), t(14, 0)),
    Act("Steve Rohbock Trio", CAFEBEIGNET, SUN, t(14, 30), t(17, 0)),
]
